### ISSUE TITLE
Remove hardcoded DB_USER in compose.yaml

### ISSUE THREAD

**Issue by EliottJaquierEdu** [CPNV-VIR1/les-jaquier#6]
When doing  
```
   healthcheck:
      test: [ "CMD", "pg_isready", "-U", "kezboard" ]
      interval: 10s
      timeout: 5s
      retries: 5
```
The kezboard user is hard coded.
Links that were visited without succes : 
https://stackoverflow.com/questions/49897503/docker-compose-invalid-interpolation-format-for-environment-option-in-service
https://stackoverflow.com/questions/54988792/docker-compose-healthcheck-use-environment-variables
https://www.postgresql.org/docs/current/app-pg-isready.html
https://stackoverflow.com/questions/46516584/docker-check-if-postgres-is-ready
https://hub.docker.com/layers/library/nginx/stable-alpine/images/sha256-26a1b20f194c2adab3be2d9e569ca837ddd31fe105d95dd51344e5bf829f1349
